// This file ensures the target has at least one Swift source file so the
// OpenAPIGenerator plugin can run. The actual API client code (Types.swift,
// Client.swift) is generated by the plugin from openapi.json.
